---
abstract: 'Easy cross-platform UNIX scripting with Perl.'
author:
  - 'Kinderfeld <archetypum@tutamail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.033, CPAN::Meta::Converter version 2.150010'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tum
requires:
  perl: '5.010'
version: '0.1'
x_generated_by_perl: v5.40.2
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: LGPL-3.0
